### PR TITLE
add prelog logging event

### PR DESCRIPTION
**Pull request by tparnell8**
Add Prelog logging event.

* Allow users to filter out events they do not wish to log
* Ability to mutate Level, and message pre-common logging
* Unit Tests

Relates to https://github.com/mperdeck/jsnlog.js/issues/21

### CODE REVIEW

**Comment by mperdeck** [comment]
Thanks for your pull request, which I have now accepted.

The next release will have this feature, but I'll probably rework it a bit:

* Your solution essentially opens up a bit of the internals to the outside world, such as the structure of LogData - essentially making this unchangeble. I'm thinking of extending the class JavascriptLogging instead, because that is very much public facing.

* I want to allow users to access more request information, such as request headers.

I think having this hook that allows the user to both extend the log message and to stop it from being logged is a great idea. Thanks for the suggestion.

**Comment by tparnell8** [comment]
Sure, Since it was a public class I didn't think it was bad to expose this to the public. If some of these things shouldn't be exposed to the consumers I would consider changing them to internal classes (and then exposing internals to your unit tests project). 

If you describe more of what you are looking for to me I don't mind doing the work myself.

**Comment by mperdeck** [comment]
Thanks for your offer. But in a burst of enthusiasm, I've already implemented it. It'll probably be released this weekend.

Following your suggestion, I've now made all private stuff internal, making the test project a friend of the main project.

**Comment by tparnell8** [comment]
Sweet!!!

**Comment by mperdeck** [comment]
The new feature has been released now. The doco is at:
http://jsnlog.com/Documentation/JavascriptLogging/OnLogging

**Comment by tparnell8** [comment]
:+1: that is awsome thanks

**Comment by tparnell8** [comment]
@mperdeck https://blog.tommyparnell.com/wiring-up-client-side-logs-into-c-sharp-logging-frameworks/

**Comment by mperdeck** [comment]
Thanks for blogging about JSNLog! Much appreciated.

**Pull request merged**
