### PR TITLE
Upgrade to rtm preview2

### PR DESCRIPTION
**Pull request by dazinator**
Have upgraded the solution in terms of tooling (xproj files, project.json files etc) as well as dependencies (ASP.NET packages updated to RTM)

# Environment / Setup

This means you will need to uninstall any RC1 / RC2 tooling that you may have installed previously, and then install [VS Update 3, and the Dotnet CLI from here](https://www.microsoft.com/net/core#windows) before opening this solution. 

# Project / Solution file changes

Previously the .xproj files were importing `DNX` targets and props. They now import the `dotnet` targets and props.

`Global.json` and `LaunchSettings.json` files have been updated.

`Project.json` files updated to the newer schema.

# Dependencies 

The dependencies on the ASP.NET RC1 (`Microsoft.AspNet.*`) have been renamed / updated to the RTM versions (Microsoft.AspNetCore.*).

# Tests

The integration tests were previously calling `Dnx.exe` to start the website running. They now use `dotnet run` to do the same. The integration tests are all passing on my environment.

# Target Frameworks

The `frameworks` that the `JsnLog` project is being compiled for --> Have removed the `Dnx` ones as these were only there for ASP.NET RC1 compatibility. Effectively have dropped support for ASP.NET RC1. Instead, now target `netstandard1.6` and `net452` in order to support ASP.NET Core RTM on those platforms. `net452` is required because this is the earliest version of .net framework on windows desktop that supports the ASP.NET Core RTM packages, but it does not support `netstandard1.6` packages, for further info about netstandard compatibility see https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

# NuGet package

Here it is: https://www.nuget.org/packages/JSNLog-dazinator/2.17.5-rtm-preview2-4

I have taken on board what you said about the last attempt at a PR, and tried to keep JsnLog as a single NuGet package. Given that you can create an ASP.NET 4 application on the same target framework as an ASP.NET Core application, it's very hard to have a single NuGet package that delivers the correct dependencies to both styles of application, given that the NuGet package only ditinguishes based on target framework. I would think long term, the best solution would be to have a seperate NuGet package for ASP.NET Core. but for the meantime this is behaviour I have tried to deliver via the one nuget package approach:

If you have a project targeting .net 4, and you install the JsnLog NuGet package, you get `System.Web` based stuff (i.e legacy ASP.NET)
If your project targets 4.5.2, you get the ASP.NET Core RTM dependencies.
If your project targets netstandard1.6, you get the the ASP.NET Core RTM stuff.

Tests are all passing EXCEPT for the DEMO ones which look like they might be hardcoded to look for an external project on your C drive?

Let me know your thoughts on this..

### CODE REVIEW

**Comment by dazinator** [comment]
Just wanted to show the tests as I see them running locally - not sure what to do about the demo ones.
image

**Comment by dazinator** [comment]
In order to fix the AppVeyor, will need to amend the build so that it first does a `dotnet restore` prior to doing a `dotnet build`..

**Comment by mperdeck** [comment]
Thanks for your pull request. Looking at it now. Have started warming to the idea of having 2 separate packages - JSNLog for ASP.NET and JSNLog.AspNetCore for ASP.NET Core.

**Comment by mperdeck** [comment]
I just released version 2.18.0, which has your changes, and introduced a new package JSNLog.AspNetCore which is Core specific. That latter package would be a replacement for your JSNLog-dazinator package.

Also updated the AspNet5 demo project (I'll rename it to AspNetCore later).

Thanks for your help in getting JSNLog updated to RC2!

**Comment by dazinator** [comment]
Nice, no problem - thank you for this useful tool.

**Pull request merged**
